# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2017
  project: XSLT Content Object
  version: 1.8.0
  release: 1.8.0
  latex_documents:
  - - Index
    - cobj_xslt.tex
    - XSLT Content Object
    - Torsten Schrade
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...